# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

theme                     : minimal-mistakes-jekyll
remote_theme              : mmistakes/minimal-mistakes@4.22.0
minimal_mistakes_skin     : "air"

# Site Settings
title                     : "Hardware for edge AI"
title_separtor            : "-"
subtitle                  :
name                      : "AiBlox BV"
description               : "An amazing website"
url                       : "https://www.ai-blox.com"
baseurl                   : "/"
logo                      : "/main/assets/images/AIBloxLogo@2x.png"
masthead_title            : "AiBlox BV"

atom_feed:
  hide                    : true


# Social Sharing
twitter:
  username                : "ai-blox"


# Site Footer
footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/ai-blox"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/ai-blox"




plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache



# Reading Files
include:
  - _pages